version: '3'
services:
  app1:
    build: ./apps/app1
    ports:
    - "5001:5000"
  app2:
    build: ./apps/app2
    ports:
    - "5002:5000"
  app3:
    build: ./apps/app3
    ports:
    - "5003:5000"
  app4:
    build: ./apps/app4
    ports:
    - "5004:5000"
  app5:
    build: ./apps/app5
    ports:
    - "5005:5000"
  app6:
    build: ./apps/app6
    ports:
    - "5006:5000"
  app7:
    build: ./apps/app7
    ports:
    - "5007:5000"
  nginx:
    build: ./nginx
    ports:
    - "8080:80"
    depends_on:
      - app1
      - app2
      - app3
      - app4
      - app5
      - app6
      - app7